name: Deploy React App
permissions:
  contents: write
  # permissions : autorisation d'écriture accordée pour les actions
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4
        # uses: emploi des actions du marketplace de GitHub
        # actions/checkout@v4 : action qui permet de cloner la dernière version du dépôt
      - name: Install Node v18
        uses: actions/setup-node@v4
        # actions/setup-node@v4 : action qui permet d'installer une version de Node.js
        with:
          node-version: 18
          # version de Node.js à installer, ici la version 18
      - name: Install dependencies
        run: npm install
        # run: npm install : commande qui permet d'installer les dépendances du projet
      - name: Build
        run: npm run build
        # run: npm run build : commande qui permet de construire le projet
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          # dossier à déployer, ici le dossier build
          branch: gh-pages
          # branche sur laquelle déployer, ici la branche gh-pages
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # ACCESS_TOKEN : variable d'environnement qui contient le token d'accès
          # secrets.ACCESS_TOKEN : secret qui contient le token d'accès
